GET http://localhost:8000/content-service/share/notice
Accept: application/json
###

GET http://localhost:8000/content-service/share/list
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/content-service/share/1
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/content-service/share/exchange
content-type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 2,
  "shareId": 22
}
###
POST http://localhost:8000/content-service/share/contribute
Content-Type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 1,
  "author": "尤雨溪",
  "title": "详解 Vue.js",
  "isOriginal": 1,
  "price": 20,
  "downloadUrl": "https://cn.vuejs.org",
  "cover": "https://img2.baidu.com/it/u=4002938427,987737150&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500",
  "summary": "详解vue.js  详解vue.js  详解vue.js  详解vue.js  "
}