server:
  port: 8000
spring:
  application:
    name: gateway-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route-user
          uri: lb://user-service
          predicates:
             - Path=/user-service/**
        - id: route-content
          uri: lb://content-service
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: 'true'
            maxAge: '3600'

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    routes:
      - name: route-user
        url: /user-service/v3/api-docs?group=user
        service-name: user-service
        order: 2
      - name: route-content
        url: /content-service/v3/api-docs?group=content
        service-name: content-service
        order: 3
